services:
  db:
    image: postgres:16-alpine
    container_name: istgahedandan_db
    environment:
      POSTGRES_USER: istgah
      POSTGRES_PASSWORD: istgah_pass_2024
      POSTGRES_DB: istgahedandan
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
